### ISSUE TITLE
Sort com opção sem sensitive case

### ISSUE THREAD

**Issue by autoforcedev** [autoforce/APIcasso#1]
Seria interessante ter uma opção na ordenação que determinasse que a ordenação não fosse sensitive case, para que coisas como **a** e **A** fiquem juntos.

**Comment by ErvalhouS** [comment]
Isso tem mais haver com o banco do que com a gema, o método de ordenação usado é uma chamada de `order()` do próprio ActiveRecord. Casos de necessidade de ordenação específica devem ser tratados no escopo do projeto com o seu próprio controller.
