### ISSUE TITLE
Sort por atributos aninhados 

### ISSUE THREAD

**Issue by autoforcedev** [autoforce/APIcasso#3]
Seria interessante que se pudesse fazer a ordenação de um elemento pela chave de um elemento hash filho dele, por exemplo

> used_model: {profile_image: {url: nil}}

Então o sort poderia ser assim

> {{url}}/{{api_base}}/used_models?q[active_eq]=true&sort=-profile_image.url

**Comment by ErvalhouS** [comment]
Isso é possível usando seletores do ransack
